format_version: v1.0
type: UniqueComponent
attributes: {id: tc0}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: SYS_TIME_COMPONENT_ID}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: sys_time}
  - type: String
    attributes: {id: SYS_TIME_PLIB_OPERATION_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: SYS_TIME_PLIB_MODE_PERIOD}
  - type: File
    attributes: {id: TC_CAPTURE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TC_CAPTURE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TC_COMPARE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: TC_COMPARE_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Compare Period is 0.4 us ****'}
  - type: File
    attributes: {id: TC_COMPARE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: TC_CTRLA_PRESCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: TC_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '60000000'}
  - type: Combo
    attributes: {id: TC_OPERATION_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Timer}
  - type: Comment
    attributes: {id: TC_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Timer resolution is 16.6666666667 nS****'}
  - type: Boolean
    attributes: {id: TC_SYS_TIME_CONNECTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'true'}
  - type: File
    attributes: {id: TC_TIMER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TC_TIMER_INTENSET_MC1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
  - type: Boolean
    attributes: {id: TC_TIMER_INTENSET_OVF}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'true'}
  - type: Long
    attributes: {id: TC_TIMER_PERIOD}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '60000'}
  - type: File
    attributes: {id: TC_TIMER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Float
    attributes: {id: TC_TIMER_TIME_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '1.0922667'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: '1.0'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: TC0_TMR}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sys_time}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: sys_time_TMR_dependency}
- type: ElementPosition
  attributes: {x: '36', y: '184', id: tc0}
